# This file is part of the Zephir.
#
# (c) Phalcon Team <team@zephir-lang.com>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

codecov:
  notify:
    # will no delay sending notifications until all ci is finished
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "65...90"

  status:
    project:
      default:
        # the amount that coverage can drop while still posting a success
        threshold: 1%
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: diff
  behavior: default
  require_changes: false

ignore:
  - ".git"
  - "*.yml"
  - "*.json"
  - "*.md"
  - "*.mk"
  - "*.txt"
  # ignore folders and all its contents
  - ".github/.*"
  - ".vscode/.*"
  - ".zephir/.*"
  - "cmake/.*"
  - "docs/.*"
  - "tests/.*"
