name: analysis

on:
  pull_request:
    branches:
      - 'master'

jobs:
  code_style:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
        with:
            fetch-depth: 1

      - uses: actions/cache@v1
        name: Setup pip cache
        id: analysis-tools-pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          version: 3.x
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cmake Check
        run: |
          cmake-format --version
          cmake-format -i $(find ./cmake -name '*.cmake')
          cmake-format -i $(find . -name 'CMakeLists.txt')
          git diff --exit-code

      - name: C++ Check
        run: |
          clang-format --version
          clang-format -i $(find ./src -name '*.cpp')
          clang-format -i $(find ./src -name '*.hpp')
          clang-format -i $(find ./include -name '*.cpp')
          clang-format -i $(find ./include -name '*.hpp')
          git diff --exit-code
