name: analysis

on:
  push:
    branches-ignore:
      - 'wip-*'
    paths-ignore:
      - 'README.md'

  pull_request:
    branches:
      - 'master'

jobs:
  code_style:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          version: 3.8
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cmake-format clang-format

      - name: Cmake Check
        run: |
          cmake-format --version
          cmake-format -i $(find . -name "*.cmake")
          cmake-format -i $(find . -name "CMakeLists.txt")
          git diff --exit-code

      - name: C++ Check
        run: |
          clang-format --version
          clang-format -i $(find . -name "*.c")
          clang-format -i $(find . -name "*.cpp")
          clang-format -i $(find . -name "*.h")
          clang-format -i $(find . -name "*.hpp")
          git diff --exit-code
