name: build

on:
  push:
    branches-ignore:
      - 'wip-*'
    paths-ignore:
      - 'README.md'

  pull_request:
    branches:
      - 'master'

jobs:
  simple_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
        fetch-depth: 5

    - name: Setup Prerequisites
      run: |
        sudo apt-get update --quiet --yes 1>/dev/null
        sudo apt-get install --no-install-recommends --quiet --yes \
            lcov          \
            libspdlog-dev \
            libyaml-cpp-dev

    - name: Configure
      run: |
        cmake                         \
            -S .                      \
            -Bbuild                   \
            -DCMAKE_BUILD_TYPE=Debug  \
            -DZEPHIR_BUILD_TESTING=ON \
            -DENABLE_ALL_WARNINGS=ON  \
            -DCODE_COVERAGE=ON
        echo ::set-env name=ZEPHIR_TESTS_ROOT::${GITHUB_WORKSPACE}/tests

    - name: Build
      run: |
        cd build
        make -j "$(getconf _NPROCESSORS_ONLN)"

    - name: Run Tests
      run: |
        cd build
        ctest -j "$(getconf _NPROCESSORS_ONLN)" --output-on-failure

    - name: Generate code coverage report
      run: |
        cd build
        make -j "$(getconf _NPROCESSORS_ONLN)" ccov-all-capture

    - name: Upload code coverage report
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./build/ccov/all-merged.info
        yml: ./.codecov.yml
