name: Simple build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Setup Prerequisites
      run: |
        sudo apt-get update --quiet --yes 1>/dev/null
        sudo apt-get install --no-install-recommends --quiet --yes \
            lcov          \
            libspdlog-dev \
            libyaml-cpp-dev

    - name: Configure
      run: |
        cmake                         \
            -S .                      \
            -Bbuild                   \
            -DCMAKE_BUILD_TYPE=Debug  \
            -DZEPHIR_BUILD_TESTING=ON \
            -DENABLE_ALL_WARNINGS=ON  \
            -DCODE_COVERAGE=ON        \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Build
      run: cmake --build build -j 10

    - name: Run Tests
      run: cd build && pwd && echo "${GITHUB_WORKSPACE}/tests" && ctest --output-on-failure
      env:
        ZEPHIR_TESTS_ROOT: "${GITHUB_WORKSPACE}/tests"
